/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ul;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

import connexion.Connexion;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

public class CalculDesRecettesForm extends javax.swing.JInternalFrame {

    public CalculDesRecettesForm() {
        
        initComponents();
        loadPeriodes();
        updateChartChiffreAffaires(title);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbPeriode = new javax.swing.JComboBox();
        lblTotalRecettes = new javax.swing.JLabel();
        lblRecettes = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCalculer = new javax.swing.JButton();
        pnlChart = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 2));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Période :");

        lblTotalRecettes.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        lblTotalRecettes.setForeground(new java.awt.Color(0, 51, 153));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Total Des Recettes :");

        btnCalculer.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        btnCalculer.setForeground(new java.awt.Color(0, 0, 153));
        btnCalculer.setText("Calculer");
        btnCalculer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(680, 680, 680)
                        .addComponent(lblRecettes))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbPeriode, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalRecettes, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCalculer, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 143, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbPeriode, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(lblTotalRecettes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalculer, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(lblRecettes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pnlChart.setBackground(new java.awt.Color(204, 255, 255));
        pnlChart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204), 2));

        javax.swing.GroupLayout pnlChartLayout = new javax.swing.GroupLayout(pnlChart);
        pnlChart.setLayout(pnlChartLayout);
        pnlChartLayout.setHorizontalGroup(
            pnlChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlChartLayout.setVerticalGroup(
            pnlChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 387, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlChart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculerActionPerformed
        // TODO add your handling code here:
        String periode = cmbPeriode.getSelectedItem().toString();
        calculerRecettes(periode);
    }//GEN-LAST:event_btnCalculerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculer;
    private javax.swing.JComboBox cmbPeriode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblRecettes;
    private javax.swing.JLabel lblTotalRecettes;
    private javax.swing.JPanel pnlChart;
    // End of variables declaration//GEN-END:variables

    
        
        

        private void calculerRecettes(String periode) {
    double total = 0;
    String sql = "";

    try {
        PreparedStatement con = Connexion.getConnection().prepareStatement(sql);

        switch (periode) {

            case "Aujourd'hui":
                sql = "SELECT SUM(c.quantite * p.prix) AS total "
                    + "FROM COMMANDE c "
                    + "JOIN PLAT p ON c.plat_id = p.id "
                    + "WHERE DATE(c.dateCommande) = CURDATE()";
                break;

            case "Cette semaine":
                sql = "SELECT SUM(c.quantite * p.prix) AS total "
                    + "FROM COMMANDE c "
                    + "JOIN PLAT p ON c.plat_id = p.id "
                    + "WHERE YEARWEEK(c.dateCommande) = YEARWEEK(CURDATE())";
                break;

            case "Ce mois":
                sql = "SELECT SUM(c.quantite * p.prix) AS total "
                    + "FROM COMMANDE c "
                    + "JOIN PLAT p ON c.plat_id = p.id "
                    + "WHERE MONTH(c.dateCommande) = MONTH(CURDATE()) "
                    + "AND YEAR(c.dateCommande) = YEAR(CURDATE())";
                break;

            case "Tout":
                sql = "SELECT SUM(c.quantite * p.prix) AS total "
                    + "FROM COMMANDE c "
                    + "JOIN PLAT p ON c.plat_id = p.id";
                break;
        }

        PreparedStatement ps = Connexion.getConnection().prepareStatement(sql);
        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            total = rs.getDouble("total");
        }

        lblTotalRecettes.setText(total + " DH");

    } catch (Exception e) {
        e.printStackTrace();
    }
}
    private void loadPeriodes() {
    cmbPeriode.addItem("Aujourd'hui");
    cmbPeriode.addItem("Cette semaine");
    cmbPeriode.addItem("Ce mois");
    cmbPeriode.addItem("Tout");
}
    
private String buildWhereClause(String periode) {
    switch (periode) {
        case "Aujourd'hui":
            return " WHERE DATE(c.dateCommande) = CURDATE() ";
        case "Cette semaine":
            return " WHERE YEARWEEK(c.dateCommande) = YEARWEEK(CURDATE()) ";
        case "Ce mois":
            return " WHERE MONTH(c.dateCommande) = MONTH(CURDATE()) AND YEAR(c.dateCommande) = YEAR(CURDATE()) ";
        default:
            return " ";
    }
}

    private void updateChartChiffreAffaires(String periode) {
    DefaultCategoryDataset dataset = new DefaultCategoryDataset();

    try {
        String sql = "SELECT p.nom, SUM(c.quantite * p.prix) as chiffreAffaires " +
                     "FROM COMMANDE c " +
                     "JOIN PLAT p ON c.plat_id = p.id " +
                     buildWhereClause(periode) +
                     "GROUP BY p.nom " +
                     "ORDER BY chiffreAffaires DESC";

        PreparedStatement ps = Connexion.getConnection().prepareStatement(sql);
        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            String plat = rs.getString("nom");
            double ca = rs.getDouble("chiffreAffaires");
            dataset.addValue(ca, "Chiffre d'affaires", plat);
        }
        JFreeChart chart = ChartFactory.createBarChart(
                "Chiffre d'affaires par plat  " + periode,
                "Plats",
                "Chiffre d'affaires (DH)",
                dataset,
                PlotOrientation.VERTICAL,
                true, true, false
        );
        chart.setBackgroundPaint(Color.WHITE);
        CategoryPlot plot = chart.getCategoryPlot();
        plot.setBackgroundPaint(Color.white);
        plot.setRangeGridlinePaint(Color.RED);
        ChartPanel chartPanel = new ChartPanel(chart);
        pnlChart.removeAll();
        pnlChart.setLayout(new BorderLayout());
        pnlChart.add(chartPanel, BorderLayout.CENTER);
        pnlChart.revalidate();
        pnlChart.repaint();
    } catch (Exception e) {
        e.printStackTrace();
    }
}
}